## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
import numpy as np
print()
print("Q1-1")
df = pd.DataFrame(data)
print(df)
print()
print("Q1-2")
df2 = df[(np.logical_or(df["job"]=="teacher", df["job"]=="psychologist") & (df["num_cars"]>df["family_size"]))]
print(df2)
print()
print("Q1-3")
df3= df[(df["family_size"]<=2)& (df["num_cars"]>=1)]
print(df3)
print()
print("Q1-4")
print(len(df.loc[:,"job"].unique()))


Q1-1
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

Q1-2
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

Q1-3
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Q1-4
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
print("Q2")
data = {'fruit': fruit, 'weights': weights}
frame = pd.DataFrame(data)
print(frame)
for i in fruit.unique():
  #print(frame.weights[frame["fruit"]==i])
  x = np.sum(frame.weights[frame["fruit"]==i])
  x = x/len(frame[frame["fruit"]==i])
  print("The mean of " + i + " is " + str(x))

Q2
    fruit  weights
0  banana      1.0
1  banana      2.0
2  banana      3.0
3  carrot      4.0
4  carrot      5.0
5  banana      6.0
6  banana      7.0
7  carrot      8.0
8  carrot      9.0
9  banana     10.0
The mean of banana is 4.833333333333333
The mean of carrot is 6.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
import pandas as pd
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
print("Q3-1")
course = pd.Series(course_name)
course.name = "Course Name"
#print(course)
print(course.sort_values())
print()
print("Q3-2")
frame = pd.DataFrame(course)
frame["Start with P"] = frame["Course Name"].astype(str).str[0] == "P"
print(frame)

Q3-1
1          JS
3         PHP
0      Python
2    examples
4        html
Name: Course Name, dtype: object

Q3-2
  Course Name  Start with P
0      Python          True
1          JS         False
2    examples         False
3         PHP          True
4        html         False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
import pandas as pd
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
print("Q4-1")
dates = pd.date_range("20130101", periods=7)
studentid = pd.DataFrame(student_id, index=np.arange(0, 7, 1), columns=["StudentID"])
Frame1 = Frame.sort_values(by=["StudentID"], ascending=True)
Frame2 = Frame.sort_values(by=["StudentID"],ascending=False)
Framex = Frame.sort_values(by=["index"], ascending=False)
print(studentid)
print(Framex)
#print(Frame1)
#print(Frame2)
print()
print("Q4-2")
print(Frame2.head(3))

Q4-1
   StudentID
0       1023
1       5202
2       6230
3       1671
4       1682
5       5241
6       4532
       StudentID
index           
6           4532
5           5241
4           1682
3           1671
2           6230
1           5202
0           1023

Q4-2
       StudentID
index           
2           6230
5           5241
1           5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
print("Q5")
print()
arr =[]
for i in range(0,100,1):
  if ((i%3==0) or (i%5==0)):
    if i in arr:
      continue
    else:
      arr.append(i)

sum=0
for i in arr:
  print(i)
  sum= sum+i
print("Sum: " + str(sum))

Q5
0
3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50
51
54
55
57
60
63
65
66
69
70
72
75
78
80
81
84
85
87
90
93
95
96
99
Sum:2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
print("Q6.1")
b= np.copy(arr)
a = np.copy(arr)
b[:,[1, 2]] = b[:,[2, 1]]
print(b)
print()
print("Q6.2")
#Q6.2
a[[0, 1]] = a[[1, 0]]
print(a)

Q6.1
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

Q6.2
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
